### ISSUE TITLE
Check if stories contain an estimation

### ISSUE THREAD

**Issue by NielsTalens** [craftsmenlabs/stories#2]
As a product manager, 
I want to see the status of estimations,
So that I can be sure my roadmap is as good as it can be.

- Also more strict for the first batch than the rest of the backlog (https://github.com/craftsmenlabs/stories/issues/6)

**Comment by YouriTjang** [comment]
note: in current dataset the estimation is stored in "customfield_10308"
Also, 1 estimation is 1.5, is this what we want?
