### ISSUE TITLE
Fillrate completeness is misbehaving

### ISSUE THREAD

**Issue by kevinvaningen** [craftsmenlabs/stories#60]
When explicitly not configured the software still throws errors on not filled items.

Reproduction:

Mapping is overriden for three items below.

Run with spring configuration: --validation.bug.filledWith="reproduction-path,expected-behavior,acceptation-criteria" 

This results in: 

Violation found: Violation(violationType=BugFieldEmptyViolation, cause=Field software was found to be empty while it should be filled.)

**Comment by Morlack** [comment]
--validation.bug.fill-fields="reproduction,expected,acceptation-criteria"

Should do the trick
